//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABSENSI_HRDBEntities : DbContext
    {
        public ABSENSI_HRDBEntities()
            : base("name=ABSENSI_HRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoryLeave> HistoryLeaves { get; set; }
        public virtual DbSet<mAPKFile> mAPKFiles { get; set; }
        public virtual DbSet<mAppParam> mAppParams { get; set; }
        public virtual DbSet<mMappingOutletDetail> mMappingOutletDetails { get; set; }
        public virtual DbSet<mMappingOutletHeader> mMappingOutletHeaders { get; set; }
        public virtual DbSet<mMenu> mMenus { get; set; }
        public virtual DbSet<mMenuAndroid> mMenuAndroids { get; set; }
        public virtual DbSet<mModule> mModules { get; set; }
        public virtual DbSet<mMoodSurvey> mMoodSurveys { get; set; }
        public virtual DbSet<mOutlet> mOutlets { get; set; }
        public virtual DbSet<mOutletHistory> mOutletHistories { get; set; }
        public virtual DbSet<mQrCode> mQrCodes { get; set; }
        public virtual DbSet<mRole> mRoles { get; set; }
        public virtual DbSet<mRoleAccess> mRoleAccesses { get; set; }
        public virtual DbSet<mSample> mSamples { get; set; }
        public virtual DbSet<mSystemConfiguration> mSystemConfigurations { get; set; }
        public virtual DbSet<mUser> mUsers { get; set; }
        public virtual DbSet<mUserRole> mUserRoles { get; set; }
        public virtual DbSet<tAbsenUser_mobile> tAbsenUser_mobile { get; set; }
        public virtual DbSet<tAbsenUser_mobile_old> tAbsenUser_mobile_old { get; set; }
        public virtual DbSet<tLeaveType> tLeaveTypes { get; set; }
        public virtual DbSet<tLogAPI> tLogAPIs { get; set; }
        public virtual DbSet<tMenuByRole> tMenuByRoles { get; set; }
        public virtual DbSet<tMoodSurveyId> tMoodSurveyIds { get; set; }
        public virtual DbSet<trackingLocation_mobile> trackingLocation_mobile { get; set; }
        public virtual DbSet<tReportingData> tReportingDatas { get; set; }
        public virtual DbSet<tScheduleEmployeesAbsence> tScheduleEmployeesAbsences { get; set; }
        public virtual DbSet<tUserLogin_mobile> tUserLogin_mobile { get; set; }
        public virtual DbSet<tUserLoginArea_Mobile> tUserLoginArea_Mobile { get; set; }
    }
}
