//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLeave
    {
        public int intHistoryLeaveId { get; set; }
        public string txtGuiIdAbsen { get; set; }
        public string txtNIK { get; set; }
        public string txtUsername { get; set; }
        public Nullable<int> intLeaveId { get; set; }
        public string txtLeaveName { get; set; }
        public string txtReason { get; set; }
        public Nullable<System.DateTime> txtTime { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
    }
}
