//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMappingOutletDetail
    {
        public int intDetailId { get; set; }
        public Nullable<int> intHeaderId { get; set; }
        public string txtPositionCode { get; set; }
        public string txtJobtitle { get; set; }
        public string txtOrgGroupCode { get; set; }
        public string txtOrgCode { get; set; }
        public string txtJobLvlCode { get; set; }
        public string txtCostCentreCode { get; set; }
        public string txtEmpType { get; set; }
        public string txtBranchCode { get; set; }
        public Nullable<int> bitActive { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public string txtInsertedBy { get; set; }
        public string txtUpdatedBy { get; set; }
    }
}
