//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mModule
    {
        public int intModuleID { get; set; }
        public string txtModuleName { get; set; }
        public string txtDescription { get; set; }
        public string txtCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public string txtUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    }
}
