//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mOutlet
    {
        public int mOutletId { get; set; }
        public Nullable<int> intOutletId { get; set; }
        public string txtOutletName { get; set; }
        public string txtLongitude { get; set; }
        public string txtLatitude { get; set; }
        public string txtBranchCode { get; set; }
        public Nullable<int> intRegionID { get; set; }
        public Nullable<int> bitactive { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public string txtUpdatedBy { get; set; }
    }
}
