//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRoleAccess
    {
        public int intRoleAccessID { get; set; }
        public Nullable<int> intRoleID { get; set; }
        public Nullable<int> intModuleID { get; set; }
        public Nullable<bool> bitEdit { get; set; }
        public Nullable<bool> bitView { get; set; }
        public Nullable<bool> bitDelete { get; set; }
        public Nullable<bool> bitPrint { get; set; }
        public string txtCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public string txtUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    }
}
