//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUser
    {
        public int intUserID { get; set; }
        public string txtUserName { get; set; }
        public string txtNick { get; set; }
        public string txtEmpID { get; set; }
        public string txtEmail { get; set; }
        public Nullable<int> intDepartmentID { get; set; }
        public Nullable<int> intLOBID { get; set; }
        public string txtCompanyCode { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public string txtDomainName { get; set; }
        public Nullable<bool> bitUseActiveDirectory { get; set; }
        public string txtPassword { get; set; }
        public string txtCreateBy { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public string txtUpdateBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
    }
}
