//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAbsenUser_mobile_old
    {
        public string txtGUI_ID { get; set; }
        public string txtGuiIdLogin { get; set; }
        public string txtDataIdGL { get; set; }
        public string txtOutletCode { get; set; }
        public string dtAbsen { get; set; }
        public Nullable<System.DateTime> dtCheckin { get; set; }
        public Nullable<System.DateTime> dtCheckout { get; set; }
        public Nullable<int> isCheckoutBySystem { get; set; }
        public string txtLongitude { get; set; }
        public string txtLatitude { get; set; }
        public string txtDeviceId { get; set; }
        public string txtUserId { get; set; }
        public string txtImg1 { get; set; }
        public string txtImg2 { get; set; }
        public Nullable<int> intBitActive { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public string txtUpdatedBy { get; set; }
    }
}
