//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAbsenUser_mobile
    {
        public string txtGUI_ID { get; set; }
        public string txtGuiIdLogin { get; set; }
        public string txtNIK { get; set; }
        public Nullable<int> intOutletId { get; set; }
        public Nullable<System.DateTime> dtCheckin { get; set; }
        public Nullable<System.DateTime> dtCheckout { get; set; }
        public Nullable<int> isCheckoutBySystem { get; set; }
        public string txtLongitude { get; set; }
        public string txtLatitude { get; set; }
        public Nullable<int> intRegionID { get; set; }
        public string txtBranchCode { get; set; }
        public string txtDeviceId { get; set; }
        public string txtDeviceName { get; set; }
        public string txtUserId { get; set; }
        public string qrCode { get; set; }
        public string txtHeaderMappingCode { get; set; }
        public string txtDetailMappingCode { get; set; }
        public Nullable<int> intBitActive { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public string txtUpdatedBy { get; set; }
    }
}
