//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLeaveType
    {
        public int typeLeaveId { get; set; }
        public string txtleaveCode { get; set; }
        public string txtleaveName { get; set; }
        public string txtKeterangan { get; set; }
        public Nullable<int> bitActive { get; set; }
    }
}
