//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLogAPI
    {
        public string txtGUIID { get; set; }
        public string txtNamaMethod { get; set; }
        public string txtParam { get; set; }
        public Nullable<int> intResult { get; set; }
        public string txtMessage { get; set; }
        public string txtResult { get; set; }
        public string txtFrom { get; set; }
        public string txtKeterangan { get; set; }
        public string txtversion { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
    }
}
