//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMoodSurveyId
    {
        public int intMoodSurveyId { get; set; }
        public string txtGUILogin { get; set; }
        public string txtNIK { get; set; }
        public Nullable<int> intMoodIdLogin { get; set; }
        public string txtMoodDescLogin { get; set; }
        public Nullable<int> intMoodIdCheckout { get; set; }
        public string txtMoodDescCheckout { get; set; }
        public Nullable<System.DateTime> dtTimeMobile { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
    }
}
