//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserLoginArea_Mobile
    {
        public string txtDetailID { get; set; }
        public string txtGUI { get; set; }
        public string employeeId { get; set; }
        public string txtBranchArea { get; set; }
        public string txtRegion { get; set; }
        public Nullable<int> bitActive { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
        public string txtInserted { get; set; }
        public string txtUpdated { get; set; }
    }
}
