//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleBotAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserLogin_mobile
    {
        public string idUserLogin { get; set; }
        public string IntCabangID { get; set; }
        public string txtGUI { get; set; }
        public string txtNameApp { get; set; }
        public string employeeId { get; set; }
        public string jabatanId { get; set; }
        public string jabatanName { get; set; }
        public string txtKodeCabang { get; set; }
        public string txtNamaCabang { get; set; }
        public string txtAreaBranchCode { get; set; }
        public string txtUserID { get; set; }
        public string txtUserName { get; set; }
        public string txtName { get; set; }
        public string txtEmail { get; set; }
        public Nullable<System.DateTime> dtLastLogin { get; set; }
        public string txtDeviceId { get; set; }
        public Nullable<System.DateTime> dtLogOut { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtInserted { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtUpdated { get; set; }
    }
}
